export const COMMENTS_FETCH_REQUEST = 'COMMENTS_FETCH_REQUEST';
export const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
export const COMMENTS_FETCH_FAILED = 'COMMENTS_FETCH_FAILED';

export const ADD_COMMENT_FETCH_REQUEST = 'ADD_COMMENT_FETCH_REQUEST';
export const ADD_COMMENT_FETCH_SUCCESS = 'ADD_COMMENT_FETCH_SUCCESS';
export const ADD_COMMENT_FETCH_FAILED = 'ADD_COMMENT_FETCH_FAILED';
